### ISSUE TITLE
Use mariadb instead of sqlite

### ISSUE THREAD

**Issue by hdsheena** [tcsvn/activity-assistant#1]
Any idea if this will still work if I'm not using the default sqlite database?

**Comment by tcsvn** [comment]
As of now it wouldn't work, because I am referencing the database only by filepath and don't support any login. But there is no fundamental hurdle to implement this. Right now my priority lies on getting a stable version out, hopefully before christmas. After that I will look into the issue!

**Comment by tcsvn** [comment]
Hey, 
this took longer than expected ^^ With the new update you should be able to use mariadb as a database. I have tested it for amd64 as well as a raspberry pi 3 with armv7. Could you please tell me if this update  fixed the issue for you?

**Comment by hdsheena** [comment]
Launching the web UI gives a 500 error with nothing in the add-on logs. Maybe I'm missing a step?

**Comment by tcsvn** [comment]
Hmm this is odd :/ Could you please reinstall the addon and try again. At the first startup you have to wait a minute until everything is initialized. You can check the output to confirm that.  Normally there should be at least some information from the startup script. Could you please provide me with further information such as:

- what device are you running Home Assistant on?
- what type of Home Assistant installation do you have (home assistant supervised, Hassio,...)

Thanks in advance :)

**Comment by hdsheena** [comment]
Raspi 2B i think, small chance it's a raspi 3.

config:

## System Health

version | core-2021.2.0b0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.4.79-v7
arch | armv7l
timezone | America/Los_Angeles

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4994
Installed Version | 1.9.0
Stage | waiting
Available Repositories | 717
Installed Repositories | 6

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | February 11, 2021, 4:00 PM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 5.10
-- | --
update_channel | beta
supervisor_version | supervisor-2021.01.7
docker_version | 19.03.13
disk_total | 57.8 GB
disk_used | 20.2 GB
healthy | true
supported | true
board | rpi2
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.2.0), Terminal & SSH (8.10.0), InfluxDB (4.0.1), Git pull (7.12), SSH & Web Terminal (7.8.0), Grafana (6.0.0), JupyterLab Lite (0.3.1), Grocy (0.11.0), AdGuard Home (3.0.0), AppDaemon 3 (5.0.1), Portainer (1.4.0), Activity-assistant (v0.0.2-alpha)

</details>

<details><summary>Lovelace</summary>

dashboards | 3
-- | --
resources | 1
views | 9
mode | storage

</details>


It goes to the first UI step, then I click connect and it tries tot load http://192.168.1.95:8000/ and gets a 500

**Comment by hdsheena** [comment]
It seems to be working now! Finally!
... now the link to the Android app won't load though.
