### ISSUE TITLE
Device selection UI

### ISSUE THREAD

**Issue by radinsky** [tcsvn/activity-assistant#3]
Hi,

Currently trying to provide a list of devices to be tracked, 
very hard to find what I need.
The window is small and not sorted, no search as well.
![image](https://user-images.githubusercontent.com/4540268/102806894-585ce280-43c6-11eb-87bf-424a98f246b7.png)

**Comment by tcsvn** [comment]
Hey,

fixed this with the latest push. Thank you for bringing this to my attention! I have focused on functionality over usability. As I am still struggling setting up a meaningful release pipeline with version tags, you have to reinstall the add-on once again for the fix ^^  I am working on this issue :)
