### ISSUE TITLE
Add sort and filter in Device selection

### ISSUE THREAD

**Issue by radinsky** [tcsvn/activity-assistant#7]
Will be nice to have filter (or at least a sort) in device selection:

![image](https://user-images.githubusercontent.com/4540268/103586436-c25ca800-4eed-11eb-9e19-66ae48704b01.png)

**Comment by tcsvn** [comment]
Yeah sorting seams very reasonable ^^ Will be included in the next update! The filter has low priority as there are more pressing issues. But maybe some time in the future, when I have a day off I'll implement it.

**Comment by tcsvn** [comment]
done
